### ISSUE TITLE
`make cluster-sync` fails due to: malformed HTTP response "SSH-2.0-OpenSSH_8.7"

### ISSUE THREAD

**Issue by andreabolognani** [kubevirt/kubevirtci#1141]
**What happened**:

After successfully running `make cluster-up` in the KubeVirt repo, `make cluster-sync` fails:

```
$ make cluster-sync
...
go version go1.21.5 linux/amd64
Sandbox is up to date
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //:push-virt-operator (0 packages loaded, 18687 targets configured).
INFO: Found 1 target...
Target //:push-virt-operator up-to-date:
  bazel-bin/push-virt-operator.digest
  bazel-bin/push-virt-operator
INFO: Elapsed time: 1.173s, Critical Path: 0.54s
INFO: 10 processes: 2 internal, 8 processwrapper-sandbox.
INFO: Build completed successfully, 10 total actions
INFO: Build completed successfully, 10 total actions
2024/02/15 17:37:43 Error pushing image to localhost:33028/kubevirt/virt-operator:devel: unable to push image to localhost:33028/kubevirt/virt-operator:devel: Get "http://localhost:33028/v2/": net/http: HTTP/1.x transport connection broken: malformed HTTP response "SSH-2.0-OpenSSH_8.7"
make[1]: *** [Makefile:158: cluster-build] Error 1
```

Connecting to the same port using netcat confirms that the process listening to it is OpenSSH instead of the registry:

```
$ nc localhost 33028
SSH-2.0-OpenSSH_8.7
```

The port however should be the correct one, as it is obtained by asking gocli directly:

```
$ docker run --privileged --net=host --rm -v /var/run/docker.sock:/var/run/docker.sock -v /lib/modules/:/lib/modules/ quay.io/kubevirtci/gocli:2402011731-4dee353 ports --prefix k8s-1.27 registry
33028
```

Asking for a complete list of ports reveals where the issue lies:

```
$ docker run --privileged --net=host --rm -v /var/run/docker.sock:/var/run/docker.sock -v /lib/modules/:/lib/modules/ quay.io/kubevirtci/gocli:2402011731-4dee353 ports --prefix k8s-1.27
5000/tcp -> 0.0.0.0:33028
5000/tcp -> :::33027
5901/tcp -> 0.0.0.0:33027
5901/tcp -> :::33026
6443/tcp -> 0.0.0.0:33026
6443/tcp -> :::33025
8443/tcp -> 127.0.0.1:8443
2201/tcp -> 0.0.0.0:33029
2201/tcp -> :::33028
30008/tcp -> 0.0.0.0:33024
30008/tcp -> :::33023
31001/tcp -> 0.0.0.0:33023
31001/tcp -> :::33022
31111/udp -> 127.0.0.1:31111
443/tcp -> 0.0.0.0:33030
443/tcp -> :::33029
80/tcp -> 0.0.0.0:33031
80/tcp -> :::33030
30007/tcp -> 0.0.0.0:33025
30007/tcp -> :::33024
```

So the registry port (5000 inside the container) is mapped to port 33028 on the host **for IPv4** and to port 33027 **for IPv6**.

My OS seems to prefer IPv6 to IPv4, so both bazel when trying to push the image and netcat in the test above are connecting to **IPv6** port 33028, which is mapped to port 2201 inside the container. Unsurprisingly, that's the OpenSSH port.

Other commands that contact the cluster work fine, because of

```
$ grep server _ci-configs/k8s-1.27/.kubeconfig 
    server: https://127.0.0.1:33026
```

Since 127.0.0.1 is used instead of localhost, the OS is forced to use IPv4 and the correct port is used.

Applying the following diff

```diff
diff --cc cluster-up/cluster/ephemeral-provider-common.sh
index 577131c47,577131c47..e44e74f84
--- a/cluster-up/cluster/ephemeral-provider-common.sh
+++ b/cluster-up/cluster/ephemeral-provider-common.sh
@@@ -75,7 -75,7 +75,7 @@@ master_ip=$(_main_ip
  kubeconfig=${BASE_PATH}/$KUBEVIRT_PROVIDER/.kubeconfig
  kubectl=${BASE_PATH}/$KUBEVIRT_PROVIDER/.kubectl
  gocli=${BASE_PATH}/../cluster-up/cli.sh
--docker_prefix=\${DOCKER_PREFIX:-localhost:$(_port registry)/kubevirt}
++docker_prefix=\${DOCKER_PREFIX:-127.0.0.1:$(_port registry)/kubevirt}
  manifest_docker_prefix=\${DOCKER_PREFIX:-registry:5000/kubevirt}
  EOF
  }
```

is an effective workaround, but this should really just work out of the box.

I will mention that I have never experienced this issue in the past, and that recently I have upgraded my host to Fedora 39. It is possible that Fedora 38 preferred IPv4 to IPv6 and now the opposite is true, triggering the issue.

Regardless, the fact that `gocli` maps the same container port to different host ports for IPv4 and IPv6 sounds like a recipe for disaster, and I can't imagine that being an intentional choice.

**Additional context**:

I have the following in my environment:

```
$ env | grep KUBEVIRT
KUBEVIRT_CRI=docker
KUBEVIRTCI_RUNTIME=docker
```

This is what my network configuration looks like:

```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 04:d9:f5:f7:e2:d9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.62/24 brd 192.168.1.255 scope global dynamic noprefixroute enp5s0
       valid_lft 19297sec preferred_lft 19297sec
    inet6 fe80::cc28:7669:9fa4:21db/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp4s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 5e:d5:2d:ca:2e:a8 brd ff:ff:ff:ff:ff:ff permaddr 54:8d:5a:92:c4:fd
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:37:a1:b6:2c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:37ff:fea1:b62c/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
5: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:6a:21:79 brd ff:ff:ff:ff:ff:ff
    inet 192.168.124.1/24 brd 192.168.124.255 scope global virbr0
       valid_lft forever preferred_lft forever
388: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1360 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet6 fe80::f25f:bdf3:b9ef:a996/64 scope link stable-privacy proto kernel_ll 
       valid_lft forever preferred_lft forever
403: vethd2b0263@if402: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether fe:29:d1:bb:50:f5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fc29:d1ff:febb:50f5/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

Please let me know if I can provide additional information that can help debug the issue.

**Environment**:

- OS: Fedora 39
- Kernel: kernel-6.7.4-200.fc39.x86_64
- KubeVirt / Kubernetes version: https://github.com/kubevirt/kubevirt/commit/0ec44afe89077fd770fe249ddf5f082588b17095

**Comment by victortoso** [comment]
I'm hitting this too. Fedora 39 as well. Workaround provided by Andrea solved here too.

**Comment by oshoval** [comment]
Thanks

@brianmcarey 
wdyt, lets create a PR with the workaround atm ? there is no reason to keep localhost which breaks for new fedora systems

**Comment by andreabolognani** [comment]
I tried again today and things seem to have been fixed in the meantime. `make cluster-sync` worked, and the port allocation appears to be correct:

```
$ docker run --privileged --net=host --rm -v /var/run/docker.sock:/var/run/docker.sock -v /lib/modules/:/lib/modules/ quay.io/kubevirtci/gocli:2409241245-d93dec16 ports --prefix k8s-1.30
8443/tcp -> 127.0.0.1:8443
2201/tcp -> 0.0.0.0:32774
2201/tcp -> :::32774
31001/tcp -> 0.0.0.0:32768
31001/tcp -> :::32768
31111/udp -> 127.0.0.1:31111
5901/tcp -> 0.0.0.0:32772
5901/tcp -> :::32772
80/tcp -> 0.0.0.0:32776
80/tcp -> :::32776
30007/tcp -> 0.0.0.0:32770
30007/tcp -> :::32770
30008/tcp -> 0.0.0.0:32769
30008/tcp -> :::32769
443/tcp -> 0.0.0.0:32775
443/tcp -> :::32775
5000/tcp -> 0.0.0.0:32773
5000/tcp -> :::32773
6443/tcp -> 0.0.0.0:32771
6443/tcp -> :::32771
```

@victortoso can you please check things on your end?

**Comment by victortoso** [comment]
> victortoso can you please check things on your end?

`make cluster-sync` has been working for me for some time now.
I had a local patch replacing `localhost` with `127.0.0.1` in several branches (...), still not sure what has changed that broke/fix this :)

**Comment by andreabolognani** [comment]
That would be fun to figure out but I'm not up for that right now :)

Since it's now working for both of us, I'll just close the issue. Thanks for checking!
